### ISSUE TITLE
Update about:addons icon?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#11]
### Steps to reproduce:

1. In your Firefox profile open `about:config`.
2. Find the pref `extensions.legacy.enabled` and make sure it is set to `true`.
3. Find the pref `devtools.chrome.enabled` and make sure it is set to `true`.
4. Go to `about:addons` > `extensions`.
5. Open the drop-down menu with the cog icon in the upper right corner and choose `Install Add-on From File`.

### Actual results:

![pioneer-news](https://user-images.githubusercontent.com/557895/37617529-a32f5c32-2b70-11e8-835f-705ed93ebd9d.png)

**Comment by rehandalal** [comment]
This is the icon I expect to see.
