### ISSUE TITLE
ReferenceError: Config is not defined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#13]
Installed **Pioneer** and this add-on, then opened Browser Console (via `Tools > Web Developer > Browser Console`), and saw the following error:

```
ReferenceError: Config is not defined             ActiveURIService.jsm:110:11
```

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/lib/ActiveURIService.jsm#L110

I don't see any other references to `Config` in the file. Not sure if we need to add something like dis:

```js
XPCOMUtils.defineLazyModuleGetter(
  this, "Config", "resource://pioneer-study-online-news-2/Config.jsm"
);
```

**Comment by rehandalal** [comment]
This should be fixed in master.
