### ISSUE TITLE
Verify async methods in extension/bootstrap.js#finishStartup()

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#14]
Randomly spotted, but noticed that some calls in /extension/bootstrap.js's `finishStartup()` have an `await _blah_.startup()`, while others don't (because they aren't `async` methods):

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/bootstrap.js#L109-L118

I did a bit of a quick scan, and it looks like the only suspect one is /extension/lib/Hosts.jsm:7 which is an `async` method, but we aren't `await`ing the value on /extension/bootstrap.js:122 above (which may not be wrong or bad):

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/lib/Hosts.jsm#L7

---

All these looked fine, but I included them here for giggles:

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/lib/NewsIndexedDB.jsm#L26

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/lib/Panels.jsm#L15

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/lib/ActiveURIService.jsm#L45

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/lib/DwellTime.jsm#L33

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/lib/Phases.jsm#L42

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/lib/SurveyWatcher.jsm#L21

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/lib/LogHandler.jsm#L33

**Comment by pdehaan** [comment]
Also, we may want to do a quick audit of some `async` methods and see if we should wrap them in a `try..catch` block. I'm trying to solve my "ReferenceError: Config is not defined #13" issue, but struggling somewhat. But it helped me debug why I was getting some `console.log()` messages and not others.

```js
  /**
   * Add-on startup tasks delayed until after session restore so as
   * not to slow down browser startup.
   */
  async finishStartup() {
    try {
      console.log("finishing startup...");
      await NewsIndexedDB.startup();
      Panels.startup();
      Hosts.startup();
      await ActiveURIService.startup();
      DwellTime.startup();
      Phases.startup();
      SurveyWatcher.startup();
      LogHandler.startup();
      console.log("finished startup");
    } catch (err) {
      console.log("OH NO!")
      console.error(err);
    }
  },
```

**Comment by rehandalal** [comment]
The only ones with awaits are the ones we need to run synchronously

**Comment by rehandalal** [comment]
closing since i don't believe there is any action required here.
