### ISSUE TITLE
Suspicious ADDONS_UNINSTALL check in /extension/bootstrap.js#shutdown()

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#15]
Just trying to give a bunch of stuff a quick 👀 and spotted this curiosity...

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/bootstrap.js#L128-L130

By itself, it seems sane, but looking at the `REASONS` object, it looks like the `ADDONS_` (plural) should possibly be `ADDON_UNINSTALL` singular (specifically L53 below):

https://github.com/mozilla/pioneer-study-online-news-2/blob/34ae34003696a8069b8ac6ba9ecf305024fa96c6/extension/bootstrap.js#L46-L55

I honestly have no idea what any of this means. I'm guessing any references to `REASONS.ADDONS_UNINSTALL` (plural) would return `null` or `undefined` and this would either do nothing, or if the `reason` was similarly undefined, it may just randomly erase the state. ¯\\\_(ツ)\_/¯ 

Also, because this is _just an object(tm)_, not sure if ESLint could ever detect something like this. Or if we'd have to use some `Map()` or `Set()` or `Symbol()` or build our own proxy type object to make sure we're using an approved key/value.

**Comment by rehandalal** [comment]
This should be fixed in master.
