### ISSUE TITLE
Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#16]
Kinda weird, but I built the latest code from master and got the following Browser Console output from the about:addons URL:

> Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host]

![browser_consolez](https://user-images.githubusercontent.com/557895/38000097-cc3ba5a2-31da-11e8-9da3-26999ac3d95c.png)

This looks like it's coming from the bowels of `getHostnameFromURI()`:

https://github.com/mozilla/pioneer-study-online-news-2/blob/7bdc90a3e45f41afd88635b884494599f612a8a6/extension/lib/Hosts.jsm#L25-L27

Since I'm on an "about:addons" pseudo-page, it may be because it's not a real page and maybe `uri.host` isn't an expected value.

https://github.com/mozilla/pioneer-study-online-news-2/blob/7bdc90a3e45f41afd88635b884494599f612a8a6/extension/lib/RankingDoorhanger.jsm#L119-L124

**Comment by rehandalal** [comment]
I was unable to replicate this. Are you still seeing this?

**Comment by pdehaan** [comment]
Haven't seen it when I built a couple times today, but that code has been tweaked lately.
Closing for right meow, and will reopen if I see it in the Browser Console again.
