### ISSUE TITLE
date should match format "date"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#18]
Look on my mediocre whois-domains.json linter, ye Mighty, and despair!:

```js
const Ajv = require('ajv');

const whoisDomains = require('./extension/whois-domains.json');

const ajv = new Ajv({allErrors: true});


const properties = {
  domain: { type: "string", minLength: 1 },
  date: { type: "string", format: "date" },
};
const schema = {
  type: "array",
  minItems: 1,
  items: {
    type: "object",
    properties,
    additionalProperties: false,
    required: Object.keys(properties)
  }
};

const validate = ajv.compile(schema);
if (!validate(whoisDomains)) {
  console.log(ajv.errorsText(validate.errors));
  process.exitCode = 1;
}
```

```sh
$ node whois-domains.schema.js

data[187].date should match format "date",
data[344].date should be string
```

Those indexes are _super_ unhelpful since they don't show me useful information, but the two offending entries are:

1. data[187].date should match format "date": `{"date": "26-06-2012", "domain": "jewsnews.co.il"}`
1. data[344].date should be string: `{"date": null, "domain": "senate.gov"}`

The problem with the first result is that the date isn't in the expected format since it's in what looks like a localized format of "DD-MM-YYYY". Possibly a non-issue if we're just blindly rendering the date string and not trying to parse it at all.

**Comment by rehandalal** [comment]
Oops. Good spot! I had to get that one date manually and I thought I had deleted the null entries. Fix incoming.

**Comment by rehandalal** [comment]
Fixed by: https://github.com/mozilla/pioneer-study-online-news-2/commit/0d5aaa2f6ee6350f5876e95e05545ad911770117
