### ISSUE TITLE
Verify the Liberal/Conservative SVG slider

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#19]
The rushlimbaugh.com site has one of the highest `avgAlign` values (at 1.0077), yet oddly only shows as 50% full on the "MORE CONSERVATIVE" slider:

![menubar_and_rush_home_-_the_rush_limbaugh_show](https://user-images.githubusercontent.com/557895/38062136-3461411a-32a7-11e8-97fd-8ed019204ea1.png)

**Comment by pdehaan** [comment]
This is what a pretty neutral site looks like (`{"avgAlign": 0.0097}`):

![fullscreen_3_28_18__5_07_pm](https://user-images.githubusercontent.com/557895/38062770-a10c78b8-32aa-11e8-8780-913c8c43a3bb.png)

**Comment by rehandalal** [comment]
Both are as expected.

As the details on the learn more page state the values go from -2 to 2. So 1.0077 is about 50%.
