### ISSUE TITLE
Don't see a doorhanger on weaselzippers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#20]
I'm in the `treatment-bias` cohort, but am not seeing the doorhanger appear on weaselzippers.
```js
{"domain": "weaselzippers.us", "avgAlign": 1.0295}, 
```

Looking at the site, and trying to debug, but cannot tell if it is because the site is served over HTTPS or because the site has a "www." subdomain but the domain above doesn't:

```
https://www.weaselzippers.us/379929-trump-sent-a-letter-to-this-little-boy-with-a-dying-father-in-great-need/
```

**Comment by rehandalal** [comment]
It's likely due to the missing `www.` I will put some logic in place to deal with that.

**Comment by rehandalal** [comment]
This should be fixed by https://github.com/mozilla/pioneer-study-online-news-2/commit/639f3cde26ca3124746b64c483b37d5bf6acbe73

**Comment by pdehaan** [comment]
Confirmed in b096d7e497cba7b43d3d6e96678a8882b5c91e51

![weasel_zippers___scouring_the_bowels_of_the_internet___weasel_zippers](https://user-images.githubusercontent.com/557895/38099076-866edce2-332e-11e8-956e-fb3472bab773.png)
