### ISSUE TITLE
Anchor tag on Learn More page could use a noopener noreferrer

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#22]
Probably low risk, but attributes are cheap to add:

```html
rel="noopener noreferrer"
```

1. https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
2. https://mathiasbynens.github.io/rel-noopener/

https://github.com/mozilla/pioneer-study-online-news-2/blob/f8956a19016ae1a7452dac49f249b5f0ff940ce4/extension/content/learn-more.html#L12

**Comment by rehandalal** [comment]
Fixed in https://github.com/mozilla/pioneer-study-online-news-2/commit/01f688682a6fbd2e3aff75bcb98be3f3fc106a27
