### ISSUE TITLE
Browser Console warnings/errors on uninstall

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#23]
I want to dig into this a bit more tomorrow, but preemptively filing now before I forget.
I have the latest **master** installed, and I'm in phase 2 of the bias cohort, and have seen the doorhanger oodles of times, but when I went to uninstall the add-on (but kept Pioneer around), I recalled seeing these flash by in my Browser Console:

```
TypeError: Hosts is undefined[Learn More]  BiasDoorhanger.jsm:127:13
TypeError: State is undefined[Learn More]  SurveyWatcher.jsm:39:11
TypeError: Hosts is undefined[Learn More]  BiasDoorhanger.jsm:127:13
TypeError: State is undefined[Learn More]  SurveyWatcher.jsm:39:11
TypeError: LogStorage is undefined[Learn More]  LogHandler.jsm:40:9
TypeError: LogStorage is undefined[Learn More]  LogHandler.jsm:40:9
```

![browser_consolez](https://user-images.githubusercontent.com/557895/38073475-0531374a-32e0-11e8-8ef9-02323310b2b7.png)

**Comment by rehandalal** [comment]
This should be fixed by https://github.com/mozilla/pioneer-study-online-news-2/commit/85264f21cebe616d606e2708f02b239ee24b9e87

**Comment by pdehaan** [comment]
No longer seeing these in b096d7e497cba7b43d3d6e96678a8882b5c91e51.
