### ISSUE TITLE
ReferenceError: getBiasTrackedHostname is not defined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#24]
Installed latest code from **master** (85264f21cebe616d606e2708f02b239ee24b9e87), and seeing this error in Browser Console after installing add-on:

```
ReferenceError: getBiasTrackedHostname is not defined[Learn More]      Hosts.jsm:49:13
ReferenceError: getBiasTrackedHostname is not defined[Learn More]      Hosts.jsm:49:13
```

https://github.com/mozilla/pioneer-study-online-news-2/blob/85264f21cebe616d606e2708f02b239ee24b9e87/extension/lib/Hosts.jsm#L37-L50

Everything looks superficially good, so I'm guessing we're probably just missing a `this.`:

```js
 isBiasTrackedURI(uri) { 
   return !!this.getBiasTrackedHostname(uri); 
 }, 
```

![menubar_and_browser_console](https://user-images.githubusercontent.com/557895/38097133-67ea69e4-3329-11e8-81d8-9c80b159748f.png)

![about_config_and_1__git_log_-1](https://user-images.githubusercontent.com/557895/38097205-95cd1604-3329-11e8-9a0d-ef472082dc73.png)

**Comment by rehandalal** [comment]
D'oh. Yes just a missing `this.`.

Fixed in: https://github.com/mozilla/pioneer-study-online-news-2/commit/24b8f4ad7722e6a927af84518a0bff92e6721771

**Comment by pdehaan** [comment]
Looks like ESLint caught this locally as well:

```
/Users/pdehaan/dev/github/mozilla/pioneer-study-online-news-2/extension/lib/Hosts.jsm
  38:9   error  'hostname' is never reassigned. Use 'const' instead  prefer-const
  49:14  error  'getBiasTrackedHostname' is not defined              no-undef
```

We should probably set up Travis-CI or Circle-CI to run linting+build add-on on each PR to catch possible syntax issues before they get merged.

**Comment by pdehaan** [comment]
No longer seeing this in b096d7e497cba7b43d3d6e96678a8882b5c91e51.
