### ISSUE TITLE
Unsafe assignment to innerHTML

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#27]
Also via ESLint:

```
/Users/pdehaan/dev/github/mozilla/pioneer-study-online-news-2/extension/content/doorhanger/doorhanger-whois.js
  27:3  warning  Read-only global 'document' should not be modified  no-global-assign
  34:3  warning  Unsafe assignment to innerHTML                      no-unsanitized/property
```

https://github.com/mozilla/pioneer-study-online-news-2/blob/24b8f4ad7722e6a927af84518a0bff92e6721771/extension/content/doorhanger/doorhanger-whois.js#L31-L38

Since we're rendering out data from `data.date` and it's just a string, not sure if we should use something like [`textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent):

```js
dateElem.textContent = date;
```

**Comment by rehandalal** [comment]
Fixed in https://github.com/mozilla/pioneer-study-online-news-2/commit/b096d7e497cba7b43d3d6e96678a8882b5c91e51

**Comment by pdehaan** [comment]
Confirmed in b096d7e497cba7b43d3d6e96678a8882b5c91e51

![100percentfedup_com___conservative_news__social_commentary_and_breaking_stories__up-to-date_election_and_legislation_news_](https://user-images.githubusercontent.com/557895/38100167-80111bf0-3331-11e8-83eb-bac84be55f7e.png)

**Comment by pdehaan** [comment]
And in a delightfully meta twist, the WHOIS doorhanger appears after you click the LEARN MORE link and go to Wikipedia to read about WHOIS:

![whois_-_wikipedia](https://user-images.githubusercontent.com/557895/38100476-5c7307f2-3332-11e8-8129-d4d2b422e791.png)
