### ISSUE TITLE
TypeError: Services is undefined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#28]
Found in b096d7e497cba7b43d3d6e96678a8882b5c91e51, but this seems super weird edge case...

I have the Pioneer study installed, and was in the "treatment-bias" study branch. Wanting to check out the "treatment-whois" study branch, I went into about:config and changed `extensions.pioneer-online-news-2.studyBranch` to `"treatment-whois"`, and then saw this in my Browser Console:

```
TypeError: Services is undefined[Learn More]  ActiveURIService.jsm:74:11
```

https://github.com/mozilla/pioneer-study-online-news-2/blob/b096d7e497cba7b43d3d6e96678a8882b5c91e51/extension/lib/ActiveURIService.jsm#L74

![menubarr](https://user-images.githubusercontent.com/557895/38099751-4494b330-3330-11e8-9af6-61591d2ff7d3.png)

**Comment by rehandalal** [comment]
I couldn't replicate this and since I can't see this happening in any real use cases I'm gonna close for now.
