### ISSUE TITLE
Error when deleting the add-on via `expirationDate`

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#31]
From the [TESTPLAN.md doc](https://github.com/mozilla/pioneer-study-online-news-2/blob/master/TESTPLAN.md#test-that-the-addon-is-correctly-uninstalled-after-expiry):

> ### Test that the addon is correctly uninstalled after expiry
> After installing all three addons there should be a pref `extensions.pioneer-online-news-2.expirationDate` that was created. If you change the value of this pref to `1` and restart, the study addon and this sideloaded patch addon should be uninstalled.

And the error dump that I spotted in Browser Console twas:

1522360232514	addons.xpi	WARN	Exception running bootstrap method shutdown on online-news@pioneer.mozilla.org: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIIdleService.removeIdleObserver]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://pioneer-study-online-news-2/lib/DwellTime.jsm :: shutdown :: line 40"  data: no] Stack trace: shutdown()@[resource://pioneer-study-online-news-2/lib/DwellTime.jsm:40](https://github.com/mozilla/pioneer-study-online-news-2/blob/master/extension/lib/DwellTime.jsm#L40) < shutdown()@jar:file:///Users/pdehaan/Library/Application%20Support/Firefox/Profiles/14g2velp.online-news-5/extensions/[online-news@pioneer.mozilla.org.xpi!/bootstrap.js:136](https://github.com/mozilla/pioneer-study-online-news-2/blob/master/extension/bootstrap.js#L136) < callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4419 < uninstallAddon()@resource://gre/modules/addons/XPIProvider.jsm:4679 < uninstall()@resource://gre/modules/addons/XPIProvider.jsm:5618 < uninstall()@resource://pioneer-study-online-news-2/PioneerUtils.jsm:367

**Comment by rehandalal** [comment]
This is fixed by https://github.com/mozilla/pioneer-study-online-news-2/commit/e977c169b30f0c0da18342207630ccbf493339ba
