### ISSUE TITLE
Some clients switched branches in the course of the study

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/pioneer-study-online-news-2#33]
I found 292 clients that have inconsistent branches in their entries -- some with all three branches, and within the same ping even. I'm discarding them for the derived datasets, but we need to figure out how this happened before we run more studies with the same treatment assignment code.

**Comment by mythmon** [comment]
In all Normandy data I've ever looked at, we have about a 1% "weirdness" rate. That is, clients that have enrolled more than once, unenrolled without ever enrolling, or existing in two branches, etc. My usual hypothesis is that there are sometimes multiple profiles with the same telemetry and/or Normandy IDs, causing multiple profiles to have their data conflated. This could happen by cloning entire systems after setting up Firefox, or simply copying a profile directory. I'm not sure the relative magnitude of "292 clients" so I'm not sure if this could explain what you saw or not.

**Comment by sunahsuh** [comment]
It's a little more than 1% in this study -- the cloned systems thing would make sense except we've seen a bunch of these happen in the same ping, so it appears there's something else going on here.
