### ISSUE TITLE
Add linter for domains.json?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#8]
Without knowing any context or, well, really anything... I'm not sure where we're getting the domains.json data from.

https://github.com/mozilla/pioneer-study-online-news-2/blob/bad2e9f9a1b8085f9da6529829ba1eff22aaae36/extension/domains.json#L1

It looks like the list has 500 items (exactly, which I doubt is a coincidence).
It looks like 288 of the domains (57.6%) have a "www." prefix.

Not sure if we should attempt to validate the list in any way (all attributes are present and fall within the acceptable ranges), or if we're getting it from a third party and don't really have control over it.
Not sure if we also need to worry about updating the list or not...

Anyways. Here's a super basic schema validator which attempts to lint the 500 items using [**ajv**](http://npm.im/ajv):

```js
const Ajv = require("ajv");
const domains = require("../extension/domains.json");

const ajv = new Ajv({allErrors: true});

const properties = {
  domain: { type: "string", minLength: 1 },
  avgAlign: { type: "number", minimum: -1, maximum: 1.1 },
  l2: { type: "number", minimum: -1, maximum: 1 },
  l1: { type: "number", minimum: -1, maximum: 1 },
  n: { type: "number", minimum: -1, maximum: 1 },
  r1: { type: "number", minimum: -1, maximum: 1 },
  r2: { type: "number", minimum: -1, maximum: 1 },
};
const schema = {
  type: "array",
  minItems: 1,
  items: {
    type: "object",
    properties,
    additionalProperties: false,
    required: Object.keys(properties)
  }
};

const validate = ajv.compile(schema);
if (!validate(domains)) {
  console.log(ajv.errorsText(validate.errors));
  process.exitCode = 1;
}
```

Not sure what exactly `avgAlign` is, or why it needs a maximum value of "1.1", but I did spot 2 domains that were failing when I foolishly assumed a maximum value of 1.0:

```js
  {
    "domain": "www.rushlimbaugh.com",
    "avgAlign": 1.0077,
    // ...
  },
  {
    "domain": "weaselzippers.us",
    "avgAlign": 1.0295,
    // ...
  }
```

**Comment by rehandalal** [comment]
An explanation is available here:
https://github.com/mozilla/pioneer-study-online-news-2/blob/master/extension/content/learn-more.html

I don't believe we need to lint this file as it was data provided by the designers of this study.
