### ISSUE TITLE
Inconsistent copyright headers in extension/lib/*.jsm

### ISSUE THREAD

**Issue by pdehaan** [mozilla/pioneer-study-online-news-2#9]
Doubt this matters, but figured it's worth filing...

Looks like we have 14 \*.jsm files in [/extension/lib/](https://github.com/mozilla/pioneer-study-online-news-2/tree/master/extension/lib) (per <kbd>$ ls -lh extension/lib/*.jsm | wc -l</kbd>), but only 50% of those files have copyright headers (per <kbd>$ git grep "MPL/2.0/" extension/lib | wc -l</kbd>):

| FILE | HAS COPYRIGHT? |
|:----|:----|
| extension/lib/ActiveURIService.jsm | ✅
| extension/lib/BiasDoorhanger.jsm | 👎
| extension/lib/DoorhangerStorage.jsm | ✅
| extension/lib/DwellTime.jsm | ✅
| extension/lib/Hosts.jsm | 👎
| extension/lib/LogStorage.jsm | ✅
| extension/lib/NewsIndexedDB.jsm | ✅
| extension/lib/Panels.jsm | 👎
| extension/lib/Phases.jsm | ✅
| extension/lib/Pioneer.jsm | 👎
| extension/lib/PrefUtils.jsm | 👎
| extension/lib/State.jsm | ✅
| extension/lib/SurveyDoorhanger.jsm | 👎
| extension/lib/SurveyWatcher.jsm | 👎

**Comment by pdehaan** [comment]
Looks like we could use something like [**eslint-plugin-header**](https://github.com/Stuk/eslint-plugin-header) to check for copyright headers.

I found 2 potential approaches/solutions:

1. Cheap check for just MPL 2.0 URL:
    ```js
    "header/header": ["error", "block", {"pattern": "http://mozilla.org/MPL/2.0/"}],
    ```

2. Check for full MPL 2.0 text:
    ```js
    "header/header": ["error", "block", [
      " This Source Code Form is subject to the terms of the Mozilla Public",
      " * License, v. 2.0. If a copy of the MPL was not distributed with this",
      " * file, You can obtain one at http://mozilla.org/MPL/2.0/. "
    ]],
    ```

On the plus side, I tried the (2) approach above and ran <kbd>$ npm run lint:js -- --fix</kbd> and it auto-added all the missing copyright headers for me (although I did have to add a blank line after the copyright notice and the first line of code).

**Comment by rehandalal** [comment]
This should not be an issue.
